/* =========================================================
   GARAGE – כל נתוני המוצרים, ניחוחות ואפסיילים
   ========================================================= */

const BASE = 'imgs';

const SCENTS = [
  { id: 'eilat',    name: 'אילת',           desc: 'בהשראת מלון רויאל ביץ\'' },
  { id: 'borabora', name: 'בורה בורה',      desc: 'ניחוח ספא יוקרתי מפנק' },
  { id: 'berlin',   name: 'ברלין',          desc: 'בהשראת הבושם אברקומבי' },
  { id: 'havana',   name: 'הוואנה',         desc: 'בהשראת חנות הבגדים קסטרו' },
  { id: 'venice',   name: 'ונציה',          desc: 'בהשראת מלון כרמים' },
  { id: 'jerusalem',name: 'ירושלים',        desc: 'ספא יוקרתי — בהשראת מלון בראשית' },
  { id: 'laguna',   name: 'לגונה ביץ\'',    desc: 'הריח הנמכר ביותר! בהשראת פינוק' },
  { id: 'miami',    name: 'מיאמי',          desc: 'בהשראת הבושם קריד' },
  { id: 'milano',   name: 'מילאנו',         desc: 'על בסיס ריח חנויות נאוטיקה' },
  { id: 'ny',       name: 'ניו יורק',       desc: 'בהשראת טום פורד בלאק' },
  { id: 'santorini',name: 'סנטוריני',       desc: 'ניחוח משכר של חופשה חלומית' },
  { id: 'palma',    name: 'פלמה דה מיורקה', desc: 'בהשראת מרכך כביסה עדין' },
  { id: 'paris',    name: 'פריז',           desc: 'בהשראת חנות הבגדים רנואר' },
  { id: 'kofifi',   name: 'קופיפי',         desc: 'כמו לובי מלון יוקרתי' },
];

/* ---- אפסיילים גלובליים ---- */
const UPSELLS = {
  'bottle-1': {
    id: 'bottle-1',
    name: 'בקבוק ריח 100 מ"ל',
    note: 'חסכון ₪10 עם ההזמנה',
    standAlonePrice: 69,
    bundlePrice: 59,
    img: `imgs/bottles-refill.png`,
    hasScent: true,
  },
  'bottle-3': {
    id: 'bottle-3',
    name: '3 בקבוקי ריח 100 מ"ל',
    note: 'חסכון ₪58 לעומת קנייה נפרדת',
    standAlonePrice: 207,
    bundlePrice: 149,
    img: `imgs/bottles-3-large.png`,
    hasScent: true,
    qty: 3,
  },
  'annual-6': {
    id: 'annual-6',
    name: 'חבילת שנה — 6 בקבוקים (600 מ"ל)',
    note: 'חסכון ₪248! ריח לכל השנה',
    standAlonePrice: 414,
    bundlePrice: 166,
    img: `imgs/bottles-6-bundle.webp`,
    hasScent: true,
    qty: 6,
  },
  'liter-bottle': {
    id: 'liter-bottle',
    name: 'בקבוק ריח ליטר',
    note: 'ריח לחודשים — חסכון על כמות',
    standAlonePrice: 329,
    bundlePrice: 289,
    img: `imgs/bottle-large.jpg`,
    hasScent: true,
  },
  'samples': {
    id: 'samples',
    name: 'ערכת 10 דוגמיות',
    note: 'גלה את הניחוח המושלם',
    standAlonePrice: 49,
    bundlePrice: 29,
    img: `imgs/bottles-refill.png`,
    hasScent: false,
  },
  'laundry': {
    id: 'laundry',
    name: 'מבשם כביסה מרוכז 250 מ"ל',
    note: 'חסכון ₪6 עם ההזמנה',
    standAlonePrice: 45,
    bundlePrice: 39,
    img: `imgs/laundry-concentrate.png`,
    hasScent: false,
  },
  'hand-cream': {
    id: 'hand-cream',
    name: 'קרם ידיים בניחוח בראשית 25 מ"ל',
    note: 'מוצר בסטים',
    standAlonePrice: 10,
    bundlePrice: 8,
    img: `imgs/hand-cream.png`,
    hasScent: false,
  },
  'g100-upgrade': {
    id: 'g100-upgrade',
    name: 'שדרג: מפיץ G100 עד 200 מ"ר',
    note: 'כיסוי פי 3 — שלם רק ₪350 נוסף',
    standAlonePrice: 649,
    bundlePrice: 649,
    img: `imgs/g100-white.png`,
    hasScent: true,
    isUpgrade: true,
    upgradeTarget: 'g100',
  },
  's1000-upgrade': {
    id: 's1000-upgrade',
    name: 'שדרג: S1000 עד 1,000 מ"ר',
    note: 'פי 2 שטח — שלם רק ₪200 נוסף',
    standAlonePrice: 1399,
    bundlePrice: 1399,
    img: `imgs/s600-diffuser.png`,
    hasScent: true,
    isUpgrade: true,
    upgradeTarget: 's1000',
  },
};

/* ---- מוצרים ---- */
const PRODUCTS = {

  /* ===== לרכב ===== */
  car: {
    id: 'car',
    name: 'מפיץ ריח נטען AirCules לרכב',
    subtitle: 'עם חיישן תנועה חכם',
    category: 'car',
    categoryLabel: 'לרכב',
    price: 349,
    origPrice: 499,
    badge: 'מבצע',
    img: `imgs/aircules-car.png`,
    thumbs: [
      `imgs/aircules-car.png`,
      `imgs/env-install-1.jpg`,
      `imgs/env-install-2.jpg`,
    ],
    hasScent: true,
    features: [
      { icon: 'ph-car', text: 'מתאים לכל רכב' },
      { icon: 'ph-usb', text: 'טעינת USB' },
      { icon: 'ph-eye', text: 'חיישן תנועה' },
      { icon: 'ph-timer', text: 'עד 45 יום לבקבוק' },
    ],
    desc: 'מפיץ הריח החכם לרכב — מריח כשנכנסים, שותק כשיוצאים. נטען דרך USB, עד 45 יום שימוש לבקבוק 100 מ"ל אחד. עיצוב מינימליסטי שמשתלב בכל רכב.',
    upsells: ['bottle-1', 'bottle-3', 'samples'],
  },

  /* ===== לבית / משרד ===== */
  g60: {
    id: 'g60',
    name: 'מפיץ ריח G60 לבית / משרד',
    subtitle: 'חשמלי • עד 50-60 מ"ר • בקבוק 100 מ"ל מתנה',
    category: 'home',
    categoryLabel: 'לבית / משרד',
    price: 299,
    origPrice: 399,
    badge: 'מבצע',
    img: `imgs/s300-with-bottle.png`,
    thumbs: [
      `imgs/s300-with-bottle.png`,
      `imgs/s300-diffuser.png`,
    ],
    hasScent: true,
    features: [
      { icon: 'ph-plug', text: 'חיבור חשמל + USB' },
      { icon: 'ph-house', text: 'עד 50-60 מ"ר' },
      { icon: 'ph-gift', text: 'בקבוק 100 מ"ל מתנה' },
      { icon: 'ph-clock', text: 'פעולה רציפה 24/7' },
    ],
    desc: 'מפיץ ריח חשמלי עוצמתי לבית ומשרד. מכסה עד 50-60 מ"ר ברציפות. מגיע עם בקבוק שמן ריח 100 מ"ל לבחירתך — מתנה!',
    upsells: ['bottle-1', 'annual-6', 'g100-upgrade'],
  },

  g30: {
    id: 'g30',
    name: 'מפיץ ריח G30 לחללים קטנים',
    subtitle: 'על סוללות • נייד • עד 30-40 מ"ר • בקבוק 100 מ"ל מתנה',
    category: 'home',
    categoryLabel: 'לבית',
    price: 329,
    origPrice: 429,
    badge: 'מבצע',
    img: `imgs/g100-diffuser.png`,
    thumbs: [
      `imgs/g100-diffuser.png`,
    ],
    hasScent: true,
    features: [
      { icon: 'ph-battery-high', text: 'פועל על סוללות' },
      { icon: 'ph-house-simple', text: 'עד 30-40 מ"ר' },
      { icon: 'ph-gift', text: 'בקבוק 100 מ"ל מתנה' },
      { icon: 'ph-arrows-out-simple', text: 'נייד — שים איפה שרוצה' },
    ],
    desc: 'מפיץ ריח נייד שפועל על סוללות — ללא תלות בשקע. מושלם לחדרי שינה, ילדים, קרוון, ואפילו בחוץ. כולל בקבוק 100 מ"ל מתנה.',
    upsells: ['bottle-1', 'bottle-3', 'samples'],
  },

  g100: {
    id: 'g100',
    name: 'מפיץ ריח G100 לחללים גדולים',
    subtitle: 'חשמלי • עד 200 מ"ר • חצי ליטר ריח מתנה',
    category: 'home',
    categoryLabel: 'לבית / משרד',
    price: 649,
    origPrice: null,
    badge: null,
    img: `imgs/g100-white.png`,
    thumbs: [
      `imgs/g100-white.png`,
      `imgs/g100-black.png`,
    ],
    hasScent: true,
    features: [
      { icon: 'ph-plug', text: 'חיבור חשמל' },
      { icon: 'ph-building', text: 'עד 200 מ"ר' },
      { icon: 'ph-gift', text: 'חצי ליטר ריח מתנה' },
      { icon: 'ph-gauge', text: 'עוצמה מתכווננת' },
    ],
    desc: 'הפתרון האולטימטיבי לבית גדול, לובי, מסעדה או חלל פתוח — עד 200 מ"ר. עוצמת ריח מתכווננת, פעולה רציפה. מגיע עם חצי ליטר שמן ריח.',
    upsells: ['liter-bottle', 'annual-6', 'laundry'],
  },

  ipad: {
    id: 'ipad',
    name: 'מפיץ ריח דגם אייפד',
    subtitle: 'חשמלי + סוללות • עד 100-150 מ"ר • 3 בקבוקי ריח מתנה',
    category: 'home',
    categoryLabel: 'לבית / משרד',
    price: 499,
    origPrice: null,
    badge: 'פופולרי',
    img: `imgs/s800-diffuser.png`,
    thumbs: [
      `imgs/s800-diffuser.png`,
      `imgs/env-office-1.jpg`,
    ],
    hasScent: true,
    features: [
      { icon: 'ph-plug', text: 'חשמל + סוללות' },
      { icon: 'ph-house', text: 'עד 100-150 מ"ר' },
      { icon: 'ph-gift', text: '3 בקבוקי ריח מתנה' },
      { icon: 'ph-device-tablet', text: 'עיצוב אייפד אלגנטי' },
    ],
    desc: 'המפיץ הגמיש ביותר — עובד גם מהחשמל וגם מסוללות. מכסה עד 150 מ"ר, בעיצוב שטוח ואלגנטי. מגיע עם 3 בקבוקי 100 מ"ל לבחירה.',
    upsells: ['bottle-3', 'annual-6', 'laundry'],
  },

  /* ===== לעסק ===== */
  s500: {
    id: 's500',
    name: 'מפיץ ריח תעשייתי S500',
    subtitle: 'פאנל זכוכית • עד 500 מ"ר • לעסקים וחנויות',
    category: 'biz',
    categoryLabel: 'לעסק',
    price: 1199,
    origPrice: 1499,
    badge: 'מבצע',
    img: `imgs/g60-diffuser.png`,
    thumbs: [
      `imgs/g60-diffuser.png`,
      `imgs/env-office-2.jpg`,
    ],
    hasScent: true,
    features: [
      { icon: 'ph-buildings', text: 'עד 500 מ"ר' },
      { icon: 'ph-shield-check', text: 'לעסקים ומלונות' },
      { icon: 'ph-sliders', text: 'עוצמה מתכווננת' },
      { icon: 'ph-frame-corners', text: 'פאנל זכוכית פרמיום' },
    ],
    desc: 'מפיץ ריח תעשייתי עם חזית זכוכית אלגנטית — מתאים לחנויות, מסעדות, לובי מלון, ספא. מכסה עד 500 מ"ר. עוצמה מתכווננת.',
    upsells: ['liter-bottle', 's1000-upgrade', 'annual-6'],
  },

  s1000: {
    id: 's1000',
    name: 'מפיץ ריח תעשייתי S1000',
    subtitle: 'עד 1,000 מ"ר • כולל ליטר ריח • לעסקים גדולים',
    category: 'biz',
    categoryLabel: 'לעסק',
    price: 1399,
    origPrice: 1699,
    badge: 'מבצע',
    img: `imgs/s600-diffuser.png`,
    thumbs: [
      `imgs/s600-diffuser.png`,
    ],
    hasScent: true,
    features: [
      { icon: 'ph-buildings', text: 'עד 1,000 מ"ר' },
      { icon: 'ph-gift', text: 'ליטר ריח כלול' },
      { icon: 'ph-sliders', text: 'עוצמה מתכווננת' },
      { icon: 'ph-star', text: 'מדרגת פרמיום' },
    ],
    desc: 'הפתרון למרחבים גדולים — מרכזי קניות, בתי מלון, אולמות ספורט. מכסה עד 1,000 מ"ר. מגיע כולל ליטר שמן ריח לבחירה.',
    upsells: ['liter-bottle', 'liter-bottle', 'annual-6'],
  },

  /* ===== חבילות ===== */
  bundle: {
    id: 'bundle',
    name: 'באנדל מפיץ חכם + שנה בישום',
    subtitle: 'חבילת שנה מלאה — מפיץ G60 + 6 בקבוקים לבחירה',
    category: 'bundle',
    categoryLabel: 'חבילה',
    price: 465,
    origPrice: 650,
    badge: 'חיסכון ₪185',
    img: `imgs/bundle-product.webp`,
    thumbs: [
      `imgs/bundle-product.webp`,
    ],
    hasScent: true,
    features: [
      { icon: 'ph-package', text: 'מפיץ G60 + 6 בקבוקים' },
      { icon: 'ph-calendar', text: 'ריח לשנה שלמה' },
      { icon: 'ph-tag', text: 'חיסכון ₪185' },
      { icon: 'ph-gift', text: 'מתנה מושלמת' },
    ],
    desc: 'הכל-כלול: מפיץ ריח G60 לבית + 6 בקבוקי ריח 100 מ"ל לבחירתך — ריח לשנה שלמה. המתנה המושלמת לעצמך או לאהובים.',
    upsells: ['bottle-1', 'laundry', 'hand-cream'],
  },

  /* ===== בקבוקים ===== */
  bottles_100ml: {
    id: 'bottles_100ml',
    name: 'בקבוקי ריח 100 מ"ל',
    subtitle: 'בחר ניחוח + כמות',
    category: 'bottles',
    categoryLabel: 'בקבוקים',
    price: 69,
    origPrice: null,
    badge: null,
    priceVariants: [
      { qty: 1, price: 69,  label: 'בקבוק אחד' },
      { qty: 2, price: 119, label: '2 בקבוקים (₪59.50 כ"א)' },
      { qty: 3, price: 169, label: '3 בקבוקים (₪56 כ"א)' },
      { qty: 5, price: 259, label: '5 בקבוקים (₪52 כ"א)' },
    ],
    img: `imgs/bottles-refill.png`,
    thumbs: [
      `imgs/bottles-refill.png`,
    ],
    hasScent: true,
    features: [
      { icon: 'ph-drop', text: 'שמן ריח טהור' },
      { icon: 'ph-timer', text: 'עד 45 יום לבקבוק' },
      { icon: 'ph-palette', text: '14 ניחוחות לבחירה' },
      { icon: 'ph-package', text: 'מחיר טוב יותר בכמות' },
    ],
    desc: 'שמני ריח טהורים ואיכותיים — בחר את הניחוח שלך מ-14 אפשרויות, ותהנה עד 45 יום של ריח נפלא. ככל שקונים יותר — חוסכים יותר!',
    upsells: ['samples', 'laundry', 'hand-cream'],
  },

  bottles_liter: {
    id: 'bottles_liter',
    name: 'בקבוק ריח ליטר',
    subtitle: 'ריח לחודשים ארוכים — חסכוני ומשתלם',
    category: 'bottles',
    categoryLabel: 'בקבוקים',
    price: 329,
    origPrice: null,
    badge: 'כלכלי',
    img: `imgs/bottle-large.jpg`,
    thumbs: [
      `imgs/bottle-large.jpg`,
    ],
    hasScent: true,
    features: [
      { icon: 'ph-drop', text: '1,000 מ"ל שמן ריח' },
      { icon: 'ph-timer', text: 'עד 450 יום שימוש' },
      { icon: 'ph-currency-ils', text: 'מחיר ₪0.33 ליום' },
      { icon: 'ph-palette', text: '14 ניחוחות לבחירה' },
    ],
    desc: 'הפתרון החכם לטווח הארוך — בקבוק ליטר מחזיק עד 450 ימים. עלות של פחות מ-₪1 ליום. אידיאלי לעסקים ולמשתמשים עם צריכה גבוהה.',
    upsells: ['samples', 'laundry', 'hand-cream'],
  },

  /* ===== מוצרים נוספים ===== */
  samples: {
    id: 'samples',
    name: 'ערכת דוגמיות — 10 יחידות',
    subtitle: 'נסה לפני שאתה מחליט',
    category: 'extra',
    categoryLabel: 'אקסטרה',
    price: 49,
    origPrice: null,
    badge: null,
    img: `imgs/bottles-refill.png`,
    hasScent: false,
    features: [
      { icon: 'ph-test-tube', text: '10 ניחוחות שונים' },
      { icon: 'ph-heart', text: 'מצא את האהוב עליך' },
      { icon: 'ph-currency-ils', text: '₪4.90 לדוגמית' },
      { icon: 'ph-gift', text: 'מתנה מקורית' },
    ],
    desc: '10 דוגמיות מניחוחות הבסטסלר של GARAGE — נסה את כולם ומצא את הניחוח שמרגיש הכי "בית".',
    upsells: ['bottle-1', 'laundry'],
  },

  laundry: {
    id: 'laundry',
    name: 'מבשם כביסה מרוכז',
    subtitle: 'בקבוק 250 מ"ל — עד 25 כביסות',
    category: 'extra',
    categoryLabel: 'אקסטרה',
    price: 45,
    origPrice: null,
    badge: null,
    img: `imgs/laundry-concentrate.png`,
    hasScent: false,
    features: [
      { icon: 'ph-washing-machine', text: 'עד 25 כביסות' },
      { icon: 'ph-drop', text: 'מרוכז ועוצמתי' },
      { icon: 'ph-heart', text: 'ריח מלון על הבגדים' },
      { icon: 'ph-leaf', text: 'עדין לעור' },
    ],
    desc: 'הפוך את הכביסה לחוויה — מבשם מרוכז עם ניחוח יוקרתי שנשאר על הבגדים. 250 מ"ל = עד 25 כביסות.',
    upsells: ['hand-cream', 'samples'],
  },

  hand_cream: {
    id: 'hand_cream',
    name: 'קרם ידיים בניחוח בראשית',
    subtitle: '25 מ"ל — מועדון ריחות יוקרה',
    category: 'extra',
    categoryLabel: 'אקסטרה',
    price: 10,
    origPrice: null,
    badge: null,
    img: `imgs/hand-cream.png`,
    hasScent: false,
    features: [
      { icon: 'ph-hand', text: 'קרם עדין' },
      { icon: 'ph-drop', text: 'ניחוח בראשית' },
      { icon: 'ph-star', text: 'מפנק ומרגיע' },
    ],
    desc: 'קרם ידיים עדין בניחוח בראשית — ריח הספא שאוהבים, עכשיו על הידיים.',
    upsells: ['laundry', 'samples'],
  },

  perfume_women: {
    id: 'perfume_women',
    name: 'בושם שמן לאישה',
    subtitle: 'ניחוח יוקרתי מרוכז',
    category: 'extra',
    categoryLabel: 'אקסטרה',
    price: 99,
    origPrice: null,
    badge: null,
    img: `imgs/perfume-oil.jpg`,
    hasScent: false,
    features: [
      { icon: 'ph-sparkle', text: 'ניחוח יוקרתי' },
      { icon: 'ph-drop', text: 'שמן מרוכז' },
      { icon: 'ph-heart', text: 'לאישה' },
    ],
    desc: 'בושם שמן מרוכז ויוקרתי — ניחוח עמוק שנשאר.',
    upsells: ['hand-cream', 'samples'],
  },

  perfume_men: {
    id: 'perfume_men',
    name: 'בושם שמן לגבר',
    subtitle: 'ניחוח יוקרתי מרוכז',
    category: 'extra',
    categoryLabel: 'אקסטרה',
    price: 99,
    origPrice: null,
    badge: null,
    img: `imgs/perfume-oil.jpg`,
    hasScent: false,
    features: [
      { icon: 'ph-sparkle', text: 'ניחוח יוקרתי' },
      { icon: 'ph-drop', text: 'שמן מרוכז' },
      { icon: 'ph-user', text: 'לגבר' },
    ],
    desc: 'בושם שמן מרוכז ויוקרתי — ניחוח עמוק שנשאר.',
    upsells: ['hand-cream', 'samples'],
  },
};

/* ---- בעת טעינה ---- */
if (typeof module !== 'undefined') {
  module.exports = { PRODUCTS, UPSELLS, SCENTS };
}
