/* Real Google reviews for GARAGE, pulled from the Google Business Profile.
 * Place: גראז' - מפיצי הריח המתקדמים בעולם
 * 5 stars from 202 reviews;
 * 150 of them are 5-star with review text and are listed below.
 * The text is verbatim customer writing — do not edit it by hand.
 * To refresh, re-scrape the profile and regenerate this file. */
const GOOGLE_PLACE = {
  name: "גראז' - מפיצי הריח המתקדמים בעולם",
  rating: 5,
  total: 202,
  writeUrl: "https://g.page/r/CTGEsrzsu850EAE/review",
};

const GOOGLE_REVIEWS = [
  {
    n: "חגית שטרית",
    t: "אודי סוכן כלבבי שרות מעולה יחס אדיב ותמיד זמין תודה רבה לאודי יש לי מנוי לריחות מגיע עד הבית פעם בחודשים לא צריכה להתעסק בזה ממליצה מאוד",
    d: "יולי 2026",
    p: "https://lh3.googleusercontent.com/a/ACg8ocLaxYdU_Y82X4WaNBCpAg6vED4kSsNKQmXp0IFDNHXb0XAUOQ=s1920-c-rp-mo-br100",
  },
  {
    n: "גילה טפרה",
    t: "שירות מעל הכל אמאאאאאא איזה ריחות לקחתי את חבילת הפרמיום וכל ניחוח העיף לי את הראש למקום אחר . כל מי שניכנס לבית שואל/ת מה זה הריח מרגישים שניכנסו לבית מלון . ושוב תודה על השירות . מומלץץץץץץץץץ באהבה והכי אמיתי🙏♥️",
    d: "יולי 2026",
    p: "https://lh3.googleusercontent.com/a/ACg8ocKf_wDd_lXofdvygOjxBS7heN1gla29RK-zCS1dIKjWjpfYEw=s1920-c-rp-mo-br100",
  },
  {
    n: "Ariel Lugasi",
    t: "רכשתי מכשיר לפני כ 4 שנים מרוצה מאוד מאוד מהרכישה המכשיר עובד חלק ללא בעיות או תקלות , מכשיר נוח עם קביעת שעות שבאלכם או זמן הפצה של ריח לפי שניות שזה ממש נוח מזמין קבוע כל מיני סוגי ריחות וכל ריח בצבע שמנים איכותיים ונעימים בטירוף ממליץ מאוד בעיניים עצומות",
    d: "יולי 2026",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjXT_1UGdxD2utPvX6bYY1tuTEHMiUbiI5mg8nqyR4UY4Te2qbBg7Q=s1920-c-rp-mo-br100",
  },
  {
    n: "klara marom",
    t: "\"רכשתי מפיץ ריח לחדר ולרכב ואני מאוד מרוצה! ריח נעים שמחזיק לאורך זמן. בנוסף, השירות היה מצוין – יחס חם, סבלנות והמון אדיבות מצד המשווק. ממליצה בחום!\"",
    d: "יולי 2026",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjUTta-6XlqpbCAjm4UGQytDTawx-vqEBOBlAnqIwiR3_8W2bXsIcw=s1920-c-rp-mo-br100",
  },
  {
    n: "אורה שמואל",
    t: "רכשתי ונהנתי והזמנתי עוד מכשיר,.השרות מעולה.מענה מהיר ואדיב",
    d: "יולי 2026",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjXrqeDbhPa00YDWrip8txPD2mH7RPnlemVKm7agJ5L2wqke7std=s1920-c-rp-mo-br100",
  },
  {
    n: "livai aouizerate",
    t: "שירות מעולה! ריח מצוין, מה לבקש יותר?",
    d: "יוני 2026",
    p: "https://lh3.googleusercontent.com/a/ACg8ocKsoOnNsqoZaxToBf6g3eTmm-KDylXrHytb3yx7Huqh7Yq1yA=s1920-c-rp-mo-br100",
  },
  {
    n: "ירון רבינוביץ",
    t: "קניתי וקיבלתי מהר מאוד עם שליח עד הבית... נראה מעולה, שירות מעולה! יאללה, הפכתי את הבית לבית מלון!!! (לפחות בריח..... חחחח)",
    d: "יוני 2026",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjUuS_g2EPawSRNFypKQZRxMC0ykSrA5pUzzDShJoJKTBnM4YrNP=s1920-c-rp-mo-br100",
  },
  {
    n: "דיקלה חלאוי",
    t: "אחלה של מוצר. שירות מדהים וטוב של אודי היקר.",
    d: "יוני 2026",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjXFy1bMbK35u12JfvXpVgHKSvSJSIJR6JeYS5b3tVOdcV-vkNkREA=s1920-c-rp-mo-br100",
  },
  {
    n: "Beno Nasser",
    t: "מכשיר מעולה קל לתפעול עם אפלקצייה בלוטוס הריחות מהממים נשאר המון ריח בחלל החדר (סלון)ממליץ מאוד נ.ב שרות מעולה",
    d: "יוני 2026",
    p: "https://lh3.googleusercontent.com/a/ACg8ocIA9CYLQGXJ4IOP0juae9nOZMyR74rdHIcazezEVDcXm5VBCg=s1920-c-rp-mo-br100",
  },
  {
    n: "Avi Tyfhi",
    t: "משלוח מהיר יחס אישי והכי חשוב שידרג לי את המשרד בריח טיל!",
    d: "יוני 2026",
    p: "https://lh3.googleusercontent.com/a/ACg8ocJpMs9WYOnNh67Gn6pzlk4Bzoc3XSA3v0WpzHMt-QV9qE4_ESYc=s1920-c-rp-mo-ba12-br100",
    lg: 1,
  },
  {
    n: "עדן כהן",
    t: "יש את הבית שלנו לפני שהכרתי את מפיץ ריח של גראז׳ ויש את הבית אחרייי זאת הייתה הקנייה הכי טובה שעשיתי ! הבית שלנו מריח כל כך טוב ריחות ממכרים וכייף גדול בבית תודה לכם על שירות וזמינות מעולים אנחנו הכי מרוצים בעולם !!",
    d: "יוני 2026",
    p: "https://lh3.googleusercontent.com/a/ACg8ocI3WXvt375UEUj4TtR-4mbC39Aan0tA2QUqQWTt14Sieo0agw=s1920-c-rp-mo-br100",
  },
  {
    n: "זהר אלהוזייל",
    t: "אני מרוצה מאוד ממפיצי הריח של חברת \"גראז'\". איכות המוצרים גבוהה, הריחות נעימים, נעימים ואינם משתלטים מדי, והם מחזיקים לאורך זמן. בנוסף, אני מרוצה מהיחס והשירות קיבלתי מענה אדיב, מהיר ומקצועי, עם נכונות לעזור ולפתור בעיות. בסך הכול מדובר בחוויה חיובית ואני ממליצה על המוצרים והשירות. לקוחה מרהט...",
    d: "יוני 2026",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjVFGozqg4w68TkuYjz67OoP43rERNVA2AbVbhMIxjSvGN65K8pB=s1920-c-rp-mo-br100",
  },
  {
    n: "Dolly Reuven",
    t: "פשוט מושלם ,אחלה מוצר,מומלץ בחום וגם השירות נהדר🥇🥇🥇🥇🥇",
    d: "יוני 2026",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjXYPs5qu49oaBPIKcQeh-UJvdnBnsFJoXJGfz27I1rpOGDT-vxpRQ=s1920-c-rp-mo-br100",
  },
  {
    n: "דקלה זר",
    t: "שרות מעולה!!! תמיד זמינים ונכונים לעזור בכל שאלה. מכשיר מצויין , שליטה מהפלאפון . ממליצה על בושם ירושלים וונציה. למרות שהכל הכל נהדר",
    d: "יוני 2026",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjWGVKQIcRAW7My9oo4jN7kwAlXC1B3tIvbdK1awc9hXsC6brp9pjQ=s1920-c-rp-mo-ba12-br100",
    lg: 1,
  },
  {
    n: "נתנאל עמרן",
    t: "ריחות נדירים ושירות מעולה",
    d: "יוני 2026",
    p: "https://lh3.googleusercontent.com/a/ACg8ocLlw1xnbfyJdmsqOzuGBt7vdHQF36ps-a1GwOv7CYBok0GFMg=s1920-c-rp-mo-br100",
  },
  {
    n: "צביקה זר",
    t: "קנינו מכשיר מפיץ ריח לבית, אחרי הרבה מכשירים שונים. המכשיר הזה פשוט מדהים! השרות נעים, ענייני, מקצוע, אדיב ומעולה! פשוט כל הכבוד!!!",
    d: "יוני 2026",
    p: "https://lh3.googleusercontent.com/a/ACg8ocI6DIFo0UcVxIvZgOPshkAMc8k6-AwT8_EaPLKnxuOVdXbnow=s1920-c-rp-mo-ba12-br100",
    lg: 1,
  },
  {
    n: "גיא כהן",
    t: "מוצר מדהים הגיע מהר והריחות היה נעימים בעולם תודה רבה לאודי היקר",
    d: "יוני 2026",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjUSnG0lBKAUuERgWQHrqnRdcOjVLtXHF2Ng4-S34X8JGR9PLDCAZg=s1920-c-rp-mo-br100",
  },
  {
    n: "ניר אקבל",
    t: "שירות אדיב משלוח בזמן ריחות באיכות גבוה",
    d: "יוני 2026",
    p: "https://lh3.googleusercontent.com/a/ACg8ocLFD8u1fXu1L-whr0HaeJF4UIH-qkM_TWFjTt70z1gtHbOEyQ=s1920-c-rp-mo-br100",
  },
  {
    n: "טליה אפריאט",
    t: "רכשתי 3 מכשירים . יש לציין שמרגע ההתעניינות השירות היה סופר מקצועי וסבלני!!! מהתאמת המכשיר לצורך האישי ולמרחב המיועד ועד להמלצת ריח. המשלוח הגיע סופר מהיר . לי באופן אישי היה חשוב שהריח יהיה דומיננטי ויורגש ולא יעלם אחרי שנייה וזה ממש כזה ריח דומיננטי,מרוכז וסופר איכותי ובנוסף אודי עזר לי בהרכבת המכשיר עד להפעלותו . אני סופר ממליצה ❤️🥹",
    d: "יוני 2026",
    p: "https://lh3.googleusercontent.com/a/ACg8ocI0NWxuqSVX8ejJNN4dYBds6bP_a-hSiXxpIEEcQ60BvdnQ_A=s1920-c-rp-mo-br100",
  },
  {
    n: "רחלי ביטון",
    t: "הריח מושלם ונדיר!! שמתי בחלל הקליניקה הלקוחות עפות על הריח נותן הרגשה יוקרתית!! אני שמחה שהזמנתי ממליצה ברמות!!! כל בית או קליניקה חובה מכשיר כזה !! נותן אווירה כיפיתת",
    d: "יוני 2026",
    p: "https://lh3.googleusercontent.com/a/ACg8ocIIJ6PwtTfiHjPIqYARUg9tPlx2BXquRAWjEMUo_siIx0l2nQ=s1920-c-rp-mo-br100",
  },
  {
    n: "Adel Arish",
    t: "ריחותתתתת נדירים !!!! מומלץ ביותר❤️❤️",
    d: "מאי 2026",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjVnfxw09vbEg04JjIKhZjV2RWokv_kORniwGvbZoF7sj8UwBMM=s1920-c-rp-mo-br100",
  },
  {
    n: "הראל לוי",
    t: "רכשתי מפיץ ריח לבית וזה באמת המכשיר הכי טוב שהיה לי ממש איכותי והריח מורגש מאוד בכל הבית וגם השירות והיחס מעולים.",
    d: "מאי 2026",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjWy-TDQNYosb2sYY770_7jHiON2lGIembQh-w04lRTzg1N1kOv3dw=s1920-c-rp-mo-br100",
  },
  {
    n: "yaron shaked",
    t: "שירות רמה גבוה! ריח מטורףףףףף תודה רבה.",
    d: "מאי 2026",
    p: "https://lh3.googleusercontent.com/a/ACg8ocKHUP7qydipGqFRTv7gB8PrdMHbY6gY7FqDw6deAH3xT9pV3Q=s1920-c-rp-mo-br100",
  },
  {
    n: "Hen Ifregan",
    t: "הזמנתי מפיץ עם 6 בקבוקי ריח אבל לפני זה אודי המקסים דיבר איתי והסביר לי איך משתמשים ומה עושים הכל בסבלנות וגם שלח סרטון הדרכה. המשלוח הגיע אליי יום אחרי ! הריח מהמם מתפזר בכל הבית משגע מרוצה מאוד תודה רבה ♥️",
    d: "מאי 2026",
    p: "https://lh3.googleusercontent.com/a/ACg8ocLkLWLkWCNCsoWzwjgy6lx7wAtLgXIAdwqxPSskf81XYKgaEw=s1920-c-rp-mo-br100",
  },
  {
    n: "Maysoon Aruqi",
    t: "חוויית הקניה הייתה נוחה ונגישה, שירות אדיב, מרוצה מאוד מהמכשיר והריחות כמו במלון, ממליץ בחום .",
    d: "מאי 2026",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjW0bG8xwEakMg-q28eIbejv6b5RySlMqIuRk_wvUunJFXX1um-BQw=s1920-c-rp-mo-br100",
  },
  {
    n: "נתנאל בננו",
    t: "אחלה של מקום הזמנתי מהם מפיץ ריח הגיע לי תוך כמה שעות מרגע ההזמנה וכל הבית ריח טוב ממליץ בחום ואחלה של שירות ואנשים",
    d: "מאי 2026",
    p: "https://lh3.googleusercontent.com/a/ACg8ocKm1rHVom3DKqjo1SU46E4AbEVWQWBg9CnyEqpvr3RjIolsMQ=s1920-c-rp-mo-br100",
  },
  {
    n: "Lital Shefi",
    t: "אחלה מוצר, קל לתפעול. ריחות מדהימים. ובעיקר שרות מעולה! תודה❤️",
    d: "מאי 2026",
    p: "https://lh3.googleusercontent.com/a/ACg8ocLq7fOvGXx66KdSyH1eA6wFoNUxBrBklU5Nv6ogobKoRIVnWQ=s1920-c-rp-mo-br100",
  },
  {
    n: "ארז אלגריסי",
    t: "אודי האלוף איזה שירות מעל למצופה מסביר ומכוון מבחינת התאמת המוצר וקשוב לצרכים של הלקוח. כיף כיף כיף ממליץ בחום",
    d: "מאי 2026",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjUuxUCkksHaDw5q9BpasrbelZItE1AQOXo-NOxAwVc16fC7BXeAog=s1920-c-rp-mo-br100",
  },
  {
    n: "Razo",
    t: "אחלה מוצר ואחלה שירות הפיץ לי ריח מטורף בכל החנות ואפליקציה ממש נוחה לשימוש.",
    d: "מאי 2026",
    p: "https://lh3.googleusercontent.com/a/ACg8ocIpHIYrIDuShm_qhW5WCqAbAMMRqbpoZt48PskDalj7MMGmfA=s1920-c-rp-mo-ba12-br100",
    lg: 1,
  },
  {
    n: "שירלי ברוך",
    t: "מומלץ מאוד! שירות אדיב, אישי ומאוד מקצועי. המכשיר עצמו אלגנטי ונוח.. הגיע אפילו עם תליה מובנית. הניחוחות מצוינים (קיבלתי דוגמיות מכל הריחות, לקח לי זמן לבחור כי הכל מריח ממש טוב) החלל פשוט מריח נפלא וכל מי שנכנס אלינו הביתה מחמיא על הריח ושואל מה זה.. יש אפקט וואוווו.. מבחינתי חובה בכל בית להשלמת העיצוב והאווירה. מושלם!!",
    d: "מאי 2026",
    p: "https://lh3.googleusercontent.com/a/ACg8ocJAq1hKLIAa_9iGivJY7UDG58BPREyodAn67uJwy8GxLizOInIt=s1920-c-rp-mo-br100",
  },
  {
    n: "ben avitan",
    t: "אנשים מדהימים נותנים שירות בצורה הכי מקצועית שיצא לי לפגוש. המכשיר שלהם והריחות שלהם מצויינים נעים לכנס לבית תודה על חווית קניה יוצאת מן הכלל",
    d: "מאי 2026",
    p: "https://lh3.googleusercontent.com/a/ACg8ocL3IoaX8CLV1-tkcIdBvg6BF3hml-I3DVtS0PAphGPXl51lNg=s1920-c-rp-mo-br100",
  },
  {
    n: "שרית בר",
    t: "מכשיר מתוחכם, עושה את העבודה בענק. מבשם חלל 50 מטר עם תקרה גובה 5 מטר,מטורף.מעלים ריחות בישול .אני בעננים. השירות והסבלנות מעל ומעבר. ממליצה בחום. חובה בכל בית !",
    d: "מאי 2026",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjUWgkvRAkNcOXkXE_F20enbB-dBf7tNBv2Eg2b6--B24qw_als=s1920-c-rp-mo-ba12-br100",
    lg: 1,
  },
  {
    n: "רונית קאשי",
    t: "המכשיר מעולה עמד על הציפוית שלי מאוד מרוצה וגם הריחות מעולים",
    d: "מאי 2026",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjWsKQeTUFGF284kZ0Fps593pfN0zT_j6Jll370LfW5Q5lMYL2ra2w=s1920-c-rp-mo-br100",
  },
  {
    n: "ציפורה לוי",
    t: "הזמנתי משלוח מהיר הופתעתי מהריחות😲 מרגע שפתחתי את הקופסא הבנתי שאני במקום הנכון🥰 הזמנתי גם לרכב קיבלתי בדיוק את ההדרכה התלהבתי,שמחה שהכרתי אותכם, כמה חשוב שיש עם מי לדבר והתייעץ הייתם בקשר איתי מתמיד עד לקבלת המוצר, תודה על הכל👌",
    d: "אפריל 2026",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjX0aefNWwjo_j3ME8aasl95BUG1AcAmr6ZDQ9ygkNacX7QmV80=s1920-c-rp-mo-br100",
  },
  {
    n: "חלי ב",
    t: "מכשיר נוח וקל לתיפעול, מגוון ריחות, מחיר הוגן והכי חשוב שירות מעולה ומענה בכל שעה.. ממולץ מאוד",
    d: "אפריל 2026",
    p: "https://lh3.googleusercontent.com/a/ACg8ocICcU_IqA5RQGK3kK66zM6L2StngAGapz5vjg-oRZTMOeQw9A=s1920-c-rp-mo-br100",
  },
  {
    n: "David Izmailov",
    t: "איכותי שירות וריח מהטובים ביותר שיצא לי להזמין,הרווחתם לקוח חדש ביושר",
    d: "אפריל 2026",
    p: "https://lh3.googleusercontent.com/a/ACg8ocKFNdaCqQI5iW2C9tR05dnHZUaS0x-CAi-GCAXu6BHSL7mSnQ=s1920-c-rp-mo-br100",
  },
  {
    n: "Lika Berman",
    t: "רוצה לפרגן לאודי על שירות פשוט מדהים! קיבלתי במתנה מפיץ ריח ופניתי אליו עם כמה שאלות – למרות שלא קניתי ממנו ישירות, קיבלתי יחס סבלני, מקצועי ונעים כאילו אני לקוחה לכל דבר. ענה לי על הכל בכיף, הסביר בצורה ברורה והיה מאוד שירותי. לא מובן מאליו בכלל – ממליצה בחום! 🙌",
    d: "אפריל 2026",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjXvTwwJdjwSzSSLu6M3AzbP7llSxrZ9hfOSW5xgTHlUHlMB2rM=s1920-c-rp-mo-br100",
  },
  {
    n: "shlomit _d",
    t: "שלום לאחר הרבה נסיונות עם כל מיני מכשירים של מפיצי ריח הגעתי למקום הנכון ולאדם הנכון. שירות מושלם. תודה רבה מאחלת לכם פרנסה בשפע. שלומית",
    d: "אפריל 2026",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjXGcZM87yXkGhzp2qDetW7bfWXmi2tz7RvqSoFli0rOX-gDeGua=s1920-c-rp-mo-br100",
  },
  {
    n: "Ebrahem Mowse",
    t: "שירות מצוין, אמין, מחירים הכי טובים שמצאתי, משלוח מהיר, חווית קנייה ושירות מצויינת, הכי טובה שנתקלתי",
    d: "אפריל 2026",
    p: "https://lh3.googleusercontent.com/a/ACg8ocJ0ujiGOfZgLqQIgSMKXuWRWU1jG8vKUBNe26D92Svu6rz23Q=s1920-c-rp-mo-br100",
  },
  {
    n: "מנו כהן",
    t: "יחס אישי ומדיוק מוצר נפלא שמח שבחרתי בכם 🙏🏻",
    d: "אפריל 2026",
    p: "https://lh3.googleusercontent.com/a/ACg8ocJzQqD1WjriQeqNdB8WT8ZSe6tY8zKHikmvEjCBwjUjSkq1Kw=s1920-c-rp-mo-ba12-br100",
    lg: 1,
  },
  {
    n: "limor limor",
    t: "שירות ברמה גבוהה, מכשור חדיש ומקצועי, והכול מלווה בניקיון וריח נעים שמרגישים בו לאורך כל היום, ריח משגע כמו בית מלון ממליצה בחום 🙏🏼🙏🏼🙏🏼",
    d: "מרץ 2026",
    p: "https://lh3.googleusercontent.com/a/ACg8ocKfsr75gC9hXBYUXtKLW-Pgsse-onD9XAxJFAhK6DpeukW8Gw=s1920-c-rp-mo-br100",
  },
  {
    n: "Maayanc28 Maayan",
    t: "ממליצה בחום על השירות של אודי יש לי 2 מפיצי ריח בבית, המשלוח תוך יומיים עד הבית! ממליצה בחום על הריחות: סנטוריני וירושלים",
    d: "מרץ 2026",
    p: "https://lh3.googleusercontent.com/a/ACg8ocLGu6MqaRcRnNRwH-jcKt9Iah6fJwXrToBDWs9U--CdsOOL=s1920-c-rp-mo-ba12-br100",
    lg: 1,
  },
  {
    n: "נתנאל בניסתי",
    t: "מטורף מגיע מהר עוצמתי מאוד קנינו לכל המשפחה מרוצים מאוד במיוחד לאלה שמעשנים בבית",
    d: "מרץ 2026",
    p: "https://lh3.googleusercontent.com/a/ACg8ocIJWT5PtPRfdXQ7VtMuwIceNzuFpMEuL4g7pXJWotER0t-Zpw=s1920-c-rp-mo-br100",
  },
  {
    n: "ייטב אלמקייס",
    t: "שירות אדיב מקצועי ברמה הכי גבוה שפגשתי מוצר מדהים תודה רבה מרוצה מאוד מאוד",
    d: "מרץ 2026",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjU7QqpdrMvGn4kADmiLNwrJcnsVl5ulI44oO9yXUUalOuFvtPz9=s1920-c-rp-mo-br100",
  },
  {
    n: "raymonde ibgui",
    t: "גראז' מפיצי הריח, צוות מעולה, אמין, שירותי. ממליצה בחום עליהם. גם בזמן המלחמה סיפקו סחורה וזה רק מוכיח מי הם. תותחים. כל הכבוד.",
    d: "פברואר 2026",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjX97CwUdnsw8nJzkDm_q1pDgVVmcih888AuWiUJj3kv1o9nbqpk=s1920-c-rp-mo-br100",
  },
  {
    n: "אתי נוי",
    t: "שרות יוצא מן הכלל תמיד זמין לשאלה נחמד ושירותי מאוד והמוצרים שלו מעולים ממליצה",
    d: "פברואר 2026",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjXHXVdixly4cF8-sL5taruaerDM_q1xxHdauUM_rSFeamVU2Id0XQ=s1920-c-rp-mo-br100",
  },
  {
    n: "NAFTALI MAIMONY",
    t: "מדהים המכשיר עצמו נדיר ריחות מטריפים פשוט מושלם והשירות זה הכי חשוב ישר עונים עוזרים ונותנים שירות מהלב שזה הכי חשוב ממליץ מאד",
    d: "פברואר 2026",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjWwqp6YpGGI-5K4qtiFgmfEcJKc80f230bOwvNLg6Bw7ojY5Kc8=s1920-c-rp-mo-ba12-br100",
    lg: 1,
  },
  {
    n: "פלורה בן שמעון",
    t: "שרות אדיב ומהיר. ממליצה בחום",
    d: "פברואר 2026",
    p: "https://lh3.googleusercontent.com/a/ACg8ocIThBl4DvotShFBN5RtoCpk683TatwTfYagk3cx4MIzIkzUEg=s1920-c-rp-mo-br100",
  },
  {
    n: "רני שגיב",
    t: "זמינות מלאה ויחס מדהים. המון סבלנות ואיכפתיות! ריחות מעולים. בקיצור-מושלם.",
    d: "ינואר 2026",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjW5TEE1EXqu-b05criM_IIF2054z1sEITycon_vcaTmaMrDIw9_Mg=s1920-c-rp-mo-br100",
  },
  {
    n: "שרית אזולאי",
    t: "אחלה מוצר מפיץ ריח נהדר ממש מרוצה",
    d: "ינואר 2026",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjXtXxGskhSoit6_wyQ8zbJ4RNDSH9HDz1yr-_iXiFchW_x1Lt4=s1920-c-rp-mo-br100",
  },
  {
    n: "נאור ביתן",
    t: "שירות מעולה ומהיר, איכות מוצר ברמה גבוהה וריחות מעלפים. בהחלט שווה כל שקל",
    d: "ינואר 2026",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjWBzcaFATkyaRqdKZaeQajr76NRSifXbGL476HUdmVtQ9UIQ9mXlA=s1920-c-rp-mo-br100",
  },
  {
    n: "מזכירות גמהק",
    t: "ריחות מטורפים. הבית והמשרד מריחים מצויין. שרות מצויין .",
    d: "ינואר 2026",
    p: "https://lh3.googleusercontent.com/a/ACg8ocKzguRqbpobSpxEG3FfZDKCHW62IdPGATYr4Lu13IcKnct5Cfw=s1920-c-rp-mo-br100",
  },
  {
    n: "אורן אייל",
    t: "קניתי מהם ריחות מדהימים מומלץ ממש שירות מדהים והריח בכל הבית ובבגדים בכללל !!!! שווה כל שקל",
    d: "ינואר 2026",
    p: "https://lh3.googleusercontent.com/a/ACg8ocJJza8aujRuOjj7lS9uNSsgo1hqNShBih0Nfq5No2BZoJ5PdQ=s1920-c-rp-mo-br100",
  },
  {
    n: "אורן עמרם",
    t: "שירות איכות אספקה מהירה ריחות מטורפים הבית מריח כמו בית מלון מומלץ ביותר תודה לכם על הכל 💪💪💪",
    d: "ינואר 2026",
    p: "https://lh3.googleusercontent.com/a/ACg8ocL18pBF7mCTei-ZqOx_2I0SevO5yt8PMDxhlRwsJ8kBf14t=s1920-c-rp-mo-br100",
  },
  {
    n: "רועי מזרחי",
    t: "כשבצעתי הזמנה למכשיר הגיע עם חבילת הריחות קיבלתי שירות מצויין! מכשיר אמין והריחות הכי נעימים! ממליץ בחום",
    d: "דצמבר 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocI0bKh87kFAKPupoE4LXF9HShfG6TAxFPpiJaAYwHwcn_nlnA=s1920-c-rp-mo-br100",
  },
  {
    n: "תומר ישי",
    t: "חווית שירות לקוח מאוד נעימה וזמינה גם אחרי כמה שנים עם מקרה של מכשיר שנשכח במגירה. מפיצים ריח מעולה ועמידים",
    d: "דצמבר 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocIV7VeQQgARqjOyRK-AkfbIgaUx3HtbliPWucd4r6iB6ccNeg=s1920-c-rp-mo-br100",
  },
  {
    n: "שני עתרי",
    t: "ריחות מדהימים שירות מעל המצופה כייף להזמין מגא'ז ממליצה בחום רב❤️",
    d: "דצמבר 2025",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjVKt2oe3kFIZBjLeI8kY1Cm2XFC8gY7AE7NjNKAIEG6Y_oCJxgfag=s1920-c-rp-mo-br100",
  },
  {
    n: "אביב סולטן",
    t: "שירות פצצה, ריחות משגעים ומשלוח סופר מהיר🔥",
    d: "דצמבר 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocIt8wm_dRHql0VGrl7aUo0uMqpecdvSBvG4-pHS6AO-HZjrmg=s1920-c-rp-mo-br100",
  },
  {
    n: "Erez Sharon",
    t: "רכשתי מפיץ ריח לעבק של אוכל קיבלתי אותו במשלוח מהיר עד הבית אחרי 3 ימים בלבד המכשיר קל לתפעול כולל אפליקציה שאפשר לשלוט בו וכמובן הריחות נעימות עזר לי בחור בשם אודי חמוד מאוד ונותן שירות מעולה אני מרוצה ואני ממליץ",
    d: "דצמבר 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocJzoThOjJhg3rSR1sK-0pAowv8jWkaEI-uhp7HvwpS0lwRmQg=s1920-c-rp-mo-br100",
  },
  {
    n: "נתנאל עדרי",
    t: "ליווי מרגע הזמנה דרך המשלוח ועד להתקנת המכשיר מומלץ בחום",
    d: "דצמבר 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocLO0OC2eTEzCasyEhCp9q6L9ju5Urpcw52JB11cwYyuc9p-eA=s1920-c-rp-mo-br100",
  },
  {
    n: "רותם מנחם",
    t: "ביצוע הזמנה בקלות , מענה מהיר , משלוח מהיר ! שירות יוצא מן הכלל וריחות להתעלף🩷🩷🩷🩷",
    d: "דצמבר 2025",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjXPnMEG_ZaKtPKtNzu7pLN4HPl9ciIxNU0eEUgEq5tsny1lPk4z=s1920-c-rp-mo-br100",
  },
  {
    n: "מזל בסון",
    t: "המכשיר נהדר הבישום כול בקבוק עים ריחות טובים עדינים ומיוחדים אין לי מילים. השירות נהדר היגיע מהר הסבלנות של אודי כול שאלה קיבלתי הסבר בסבלנות ונתן לי ביטחון לקנות אצלכם מכשיר ובשמים טובים נהדרים.",
    d: "דצמבר 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocK2MC7tvAaGlxFA_YgBNNLJN29YtxQ6hzd9pGhzTEsF-RHvBA=s1920-c-rp-mo-br100",
  },
  {
    n: "אבי נונה",
    t: "רציתי לשבח את השירות המדהים שקיבלתי תמיד יש מענה מהיר לכל שאלה ששאלתי הריחות מדהימים לקחתי את החבילה הפרימיום תענוג של ריחות כולם מופתעים שמגיעים אלי הביתה שווה ממליץ בחום",
    d: "דצמבר 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocLP3aZigVUG48MF3aWM9AwD9m59Z5sFvRmv92hemAUBtTbe2A=s1920-c-rp-mo-br100",
  },
  {
    n: "חגית מזרחי",
    t: "רכשתי את מפיץ הריח. מכשיר מעולה, ריחות מעולים ושירות אדיב, מקצועי, יחס אישי ממליצה בחום",
    d: "דצמבר 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocKHSktMcCMhq3RqISUStizsfKHMXdFoYcSK2XsJvf3c3iwReg=s1920-c-rp-mo-br100",
  },
  {
    n: "אילנית אריה",
    t: "השירות מקסים. המשלוח הגיע כמצופה והריחות ממכרים.תודה רבה .ממליצה מאוד",
    d: "דצמבר 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocIsf7_mOF-bdm4_MMoQ3ynhf2rm1XgpA19__mkcOZSKsKeCgA=s1920-c-rp-mo-br100",
  },
  {
    n: "ariel ohanaa",
    t: "המפיצי ריח הכי טובים נשארים במשך שעות והכי כיף לחזור לבית עם ריח כזה ממליצה בחום❤️❤️❤️❤️",
    d: "נובמבר 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocL6AknCF01Zlii7HAt8C_XH9XrO0FLz0u9CFDJ2iwjDxGINwg=s1920-c-rp-mo-br100",
  },
  {
    n: "דרומקס שיווק נדלן ויזמות",
    t: "היתה לי חוויה נהדרת איתם- ממליצה",
    d: "נובמבר 2025",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjW6xIQ1DBAIhZl62wcCJSbOTI2TqjK7jEknG_CD8ufKBK5D1OQqaA=s1920-c-rp-mo-br100",
  },
  {
    n: "נוי אוטמזגין",
    t: "אין על המפיצי ריח שלכם!!! בכל פעם שנכנסים הביתה מרגישים בבית מלון!!! מכורה",
    d: "נובמבר 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocK79zKQox2LgXV9Q0YPhDDlO2RdhVJWnQFq26TIkTkpvAX2vA=s1920-c-rp-mo-br100",
  },
  {
    n: "קרולין מרציאנו",
    t: "שירות ויחס מעולה תמיד זמינים לכל שאלה ושירו מחירים מעולים אני מכורה!",
    d: "נובמבר 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocLcKj043CAO5xpVYsoCgIFFb97x-S9oogCA6W2vrisgyCMxPA=s1920-c-rp-mo-br100",
  },
  {
    n: "שירה טלולקר",
    t: "שירות מעולה והריחות אין אחד שלא נכנס לבית שלי ושואל מה זה הריח הזה ממליצה בחום",
    d: "נובמבר 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocJkf0D3IjOU_bsMdt-Zc4rv65QXq9rIS2X6udtrQSxS9mch_Q=s1920-c-rp-mo-br100",
  },
  {
    n: "שליו tc",
    t: "רוכשת כבר מספר פעמים שרות מצוין מומלץ בחום",
    d: "נובמבר 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocJirqS053FKP63BblRh56UNhFKFeyeNSt-r5Jdr8QqaDouj-A=s1920-c-rp-mo-br100",
  },
  {
    n: "יוסי יונה",
    t: "שרות מעולה.עזר לי בכל .תודה אודי .אין עליכם.",
    d: "נובמבר 2025",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjW3SiATsOPp4fKUmEV9xRZhA3Azo5T8aLL1fQXKOkbWGhndMlPTSQ=s1920-c-rp-mo-br100",
  },
  {
    n: "חני בובליל",
    t: "שירות מושלם ואמון מלא בבעל העסק שהוא איש חביב ואחראי במיוחד. אפס תקלות!",
    d: "נובמבר 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocJD1l1Ym0pMtf3a04gMkDiBoOVI3NT0kfI_yy0A0UqOtS68aw=s1920-c-rp-mo-br100",
  },
  {
    n: "גיה אביגיל",
    t: "שירות מעולה, כול שאלה ששאלתי קיבלתי ישר תשובה, וגם המוצר הגיע אליי לפניי הזמן בקיצור שירות מעולה .",
    d: "נובמבר 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocIcP33_w4WfSoB0NPLs2kqIDq4eRvjLe3C9SVxLnrr3l6CCbg=s1920-c-rp-mo-br100",
  },
  {
    n: "מורן אוחיון",
    t: "קודם כל השירות מעולה ואדיב מאוד! המוצר ממש מעולה! ממליצה בחום רב!!! רכשתי חבילה לשנה המכשיר עובד מצויין והריחות מעולים! ממליצה בחום🫶",
    d: "נובמבר 2025",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjUyQc1n9Zfl2QI2uqk6o6YMCw4fms-4B4MK7EVqufNZ0kq00ohY=s1920-c-rp-mo-br100",
  },
  {
    n: "רויטל זורנו",
    t: "שירות אדיב מהיר הסבר מפורט מכשיר קל לתפעול ריחות מצוינים אין ספק שאזמין שוב",
    d: "נובמבר 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocKmqis1uF5zo9a2L7XKm3COZoFJavnK00z2_QB4UwEsHNmBSQ=s1920-c-rp-mo-br100",
  },
  {
    n: "יהודית בן שיטרית",
    t: "חוויה של קניה שרות אדיב ומהיר.",
    d: "אוקטובר 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocKJuSsVMG-zK1aDHH4jeurQYglJb1N2bmSRX6hrihlXAsMN4Q=s1920-c-rp-mo-br100",
  },
  {
    n: "אסתר זפרני",
    t: "יחס אנושי ואכפתי, מענה בסבלנות שירות מעל למצופה!! אחזור ואזמין מכם ללא ספק👏",
    d: "אוקטובר 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocIWA0LSbPD7EIlrk2buhn6D9AWZMdhkVmIMS1PdO5RC14dX4w=s1920-c-rp-mo-br100",
  },
  {
    n: "יניר בן מוחה",
    t: "הגיע מהר מאוד כלל הסבר טלפוני וסרטונים ממליץ מאוד",
    d: "אוקטובר 2025",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjW2NuTHHjUMcQlqgWmGhBJWb7eOMsdFGewWNylO4SiIPVBENUNv=s1920-c-rp-mo-br100",
  },
  {
    n: "דוד יחיה",
    t: "שירות מעולה מקצועי שילוח מהיר והכי חשוב ריח מדהים מומלץ",
    d: "אוקטובר 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocJEclnaoOEURa7y6xREOL-3UdQ1_PZaMwcEDsEltbD-ypk6oA=s1920-c-rp-mo-br100",
  },
  {
    n: "גילי מסיקה",
    t: "שירות ואיכות ברמה הכי גבוהה תודה לכם",
    d: "אוקטובר 2025",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjVg6IU6sWowHK_Rd64Csh4g2mrUeRfpxIdYBwa94ko98QuOsxRKMg=s1920-c-rp-mo-br100",
  },
  {
    n: "רותם Rotem מלחי malhi",
    t: "‏שירות מעולה זה לא פעם ראשונה שאני קונה ממנו ‏תודה רבה לך 🫵",
    d: "אוקטובר 2025",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjUom-BRuU2Izfqg92ilZlpZtBAMR8OOmuO3vxR-rx0RSRuM5ajvXQ=s1920-c-rp-mo-br100",
  },
  {
    n: "איתן סלומון",
    t: "יחס ושירות ברמה גבוהה מוצרים איכותיים וריחות של מלון מעבר למצופה! תודה רבה על הכל ! אמשיך להזמין עוד בהמשך",
    d: "אוקטובר 2025",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjVjwD6oSHjUhvdK7HG1zPtjdyjPSoaIyRE5VxpLCo0BfNBIbACX=s1920-c-rp-mo-br100",
  },
  {
    n: "Awadhmude",
    t: "מוצר הגיע בזמן איכותי ריח נעים מאוד שירות מאודי היקר מצויין תודה רבה",
    d: "ספטמבר 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocK1ObF9tMnTG2V21J_iWA8q5WycmjUt00mpZao7JYCVsXiwXw=s1920-c-rp-mo-br100",
  },
  {
    n: "יקיר שמול",
    t: "משלוח מהיר וריחות מצויינים מומלץ בחום",
    d: "ספטמבר 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocI6SnKtKygAgtQeiRwwPvykaYYAgI_mmYlI2SqW48QMugPJksJ6=s1920-c-rp-mo-ba12-br100",
    lg: 1,
  },
  {
    n: "Liron Buzaglo",
    t: "מומלץ שירות אדיב , עונה בכל שעה , מקשיב ,וסבלני ריח מטורף",
    d: "ספטמבר 2025",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjU84ma3xrPxS3z4s4-DZQCL7xkc7kXzGuITjcD8uBX2urGv6F5e=s1920-c-rp-mo-br100",
  },
  {
    n: "Efrat Zohar",
    t: "אין כמו רושם ראשוני!!!! תודה על משלוח מהיר וריחות מטורפים ומכשיר קטן וחתיך היישר לקליניקה שלי!!!! ממליצה בחום רב עצה ממני? חבילת פרימיום זה מאסטטטטט",
    d: "ספטמבר 2025",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjVsC1Ewk_i_ZhcuLe4nIskCQMxhWZU2XeWfgP68wSU5m0eGZe5d=s1920-c-rp-mo-br100",
  },
  {
    n: "חנית לחמני",
    t: "מדהים ממש הגיע בזמן ומוצר טיל תודה",
    d: "אוגוסט 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocL-Qy6ZD4zcigX8MKFmV0h3TsJAYMzxDE-WtPQHAZ_Bc7Gm81k=s1920-c-rp-mo-br100",
  },
  {
    n: "יפת פירוז",
    t: "שרות מצוין גם במענה גם במשלוח וגם ביחס מומלץ מאוד מי ניסיון",
    d: "אוגוסט 2025",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjWp6zyW9-U56V6DB5cevx6biTDVfaJ-B5cRHXJC-cCU0rB44Or21w=s1920-c-rp-mo-ba12-br100",
    lg: 1,
  },
  {
    n: "Jenia Belov",
    t: "סוף סוף מצאנו שמן איכותי, כל השמנים שהיינו קונים עד עכשיו לא אומדים לייד האיכות ואוצמתיות שלכם. 💪🏻",
    d: "אוגוסט 2025",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjVri1iBTNhvJMIHtzjP5bMJoGxEmMJ7ZlDKGfiemlfh9WGQ0kk=s1920-c-rp-mo-ba12-br100",
    lg: 1,
  },
  {
    n: "Shalom210667@walla.com Sm123123",
    t: "רכשתי מפיץ ריח פעמיים ותמיד הייתי מרוצה מאודדד שרות ומוצר מצויינים ממליץ מאוד לכל בית תודה ושוב תודה",
    d: "יולי 2025",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjUHKQu6xjPq8mgJTmMNdTUH7UaQGohNE9lzVEdAAzhyfzRwTetKTw=s1920-c-rp-mo-ba12-br100",
    lg: 1,
  },
  {
    n: "אלי דאנינו",
    t: "המכשיר מעולה ! השמנים ריחות נפלאים שירות פנטסטי מענה מהיר מומלץ ביותר",
    d: "יולי 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocJNCHMBF0CysTk0E3sBanaFw51cP8F55VrqL4LSyDf642LkGw=s1920-c-rp-mo-br100",
  },
  {
    n: "הילה דיוט",
    t: "תודה רבה על המכשיר והשירות הנהדר! המכשיר פשוט מעולה,נוח לשימוש והשירות היה מקצועי,מהיר ואכפתי. אין עליכם!",
    d: "יולי 2025",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjWt7PJxkS9LrYDQKrvVHjb9QtjSJNdIYhr6NnzuvVmnuNZwFp1w=s1920-c-rp-mo-br100",
  },
  {
    n: "Bani Dana",
    t: "שירות מהיר הגיע בזמן עונים על כל שאלה",
    d: "יולי 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocImu5eQ58Iu8e_B8ZHePmtuVM7byQ6NwR9FXbyPPe1GwbJqrw=s1920-c-rp-mo-br100",
  },
  {
    n: "רביטל מאור",
    t: "מוצר מעולה שירות אדיב מהיר ויעיל ממליצה בחום",
    d: "יולי 2025",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjWCBxGh9K2Rx1ou1FunhlVU3nfV3Jw_VqJJeuIhC8tAqGeexd5pfA=s1920-c-rp-mo-br100",
  },
  {
    n: "שני שרביט",
    t: "מכשיר מושלם עושה ריח ממש טוב בעסק מרוצה ממנו מאוד",
    d: "יולי 2025",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjUSspc1lv8arAhI5kP0DQ7wRUGR8y_Y4OIj595ai1OD0vwoEwiL=s1920-c-rp-mo-br100",
  },
  {
    n: "Nurit Franko",
    t: "שירות ואמינות מעולים והריח בבית וואווו",
    d: "יולי 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocILr6_K3UWljGSd9ixHMWEq0VYcMupOAndTO7ZBEag4Z8gj0g=s1920-c-rp-mo-br100",
  },
  {
    n: "רן טייטלר",
    t: "קניתי מכשיר ו6 בקבוקים של שמן מומלץ קומפקטי קל לשימוש אנחנו אהבנו את ריח הלגונה ביץ אמשיך לקנות מכם בוודאות 🙏🏼",
    d: "יוני 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocJnbZFb5j4StLe4wrBK8Tn24yH7O4WnKjvjRF6IknkPeJiQgQ=s1920-c-rp-mo-br100",
  },
  {
    n: "JOHNNYTISH21 STUDIOTWENTYONE",
    t: "חוויה מצויינת משלוח זריז שירות אדיב ומהיר 🖤🧡❤️ממליץ בחום",
    d: "מאי 2025",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjWL5Cu-rdGOhA_stHPQTxV8wTUzFO9W0jGKhxCqVMop8HsEhoA=s1920-c-rp-mo-ba12-br100",
    lg: 1,
  },
  {
    n: "אופירה פרץ",
    t: "שירותיים בטירוףףף וריחות סוףףף מומלץ בחוםםם",
    d: "מאי 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocIxK2xsVU-sNN_5roM21FPPFlSgiG7S9kyIV5bX8Chyq9pigA=s1920-c-rp-mo-br100",
  },
  {
    n: "Miriam Church",
    t: "מוצרים מעולים ושירות vip ומקצויי",
    d: "מאי 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocLu1NdvmMFNuvAhmovAA8Q4FbwxNtYbuKXHK_9bDMA9EM2BEA=s1920-c-rp-mo-br100",
  },
  {
    n: "שולי ניקסן",
    t: "קיבלתי היום את המפיץ ריח. עם ריח מדהים של בית מלון. מומלץ היותר🌹",
    d: "מאי 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocIHxGo2dVGgff01Pq8X1VZvxX5DZw_4TgFyhpTAniW7P9xdqg=s1920-c-rp-mo-br100",
  },
  {
    n: "חיים לזמי",
    t: "הזמנתי דרך האתר, הגיע נציג עם דגימות ריח ומכשירים בשלל צבעים, היה סבלני, מסביר פנים ומקצועי. רכשתי 2 וממליץ בחום.",
    d: "מאי 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocLeWCAq19I6Kc1Iul7EdxY2kVQ_0ZPOhKSH0lOArPzwoiiG3Z0=s1920-c-rp-mo-br100",
  },
  {
    n: "סמי לזמי",
    t: "הגיע עד המשרד שלי ונתן שירות מעולה. מומלץ בחום אחרי שרכשנו 8 יחידות",
    d: "מאי 2025",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjXAPvimoPGYqm7qt-NsOavY0XlbhJVproHykwGsCPjDY2GMGKw=s1920-c-rp-mo-br100",
  },
  {
    n: "תמיר סטטוס לוי",
    t: "נתן לי שירות עד המספרה. אחלה ריחות ואחלה מכשיר",
    d: "מאי 2025",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjXH--VAo7KM1qRorJutxrZxMY_7S1J8JVJfynpQZojz5lfu1lM=s1920-c-rp-mo-br100",
  },
  {
    n: "סיגל סרוסי",
    t: "רכשתי כמה מכשירים כולם מושלמים והריחות סוף הדרך ומהחשוב מכל השרות ..שירות אדיב ומהיר",
    d: "מאי 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocJ20sdCiKC0B4Iy0cKOHF3sIobnEZZ3VGmv0j_neMRCzSfgsw=s1920-c-rp-mo-br100",
  },
  {
    n: "משה אברג'ל",
    t: "הכי טובים שייש. לפני כשנה קניתי שני מפיצי ריח ושמנים.באמת תענוג. איכות ושירות 10. מומלץ מאוד",
    d: "אפריל 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocJAA8MuhJw5QSlfRx_B9tOtxlS8jjEJhmpq0wrGQN2CqsaJdQ=s1920-c-rp-mo-br100",
  },
  {
    n: "רואי אילוז",
    t: "אחלה שירות ואחלה ריחות. ממליץ בחום🔥🔥🔥",
    d: "אפריל 2025",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjWcuxeepKNX_vyFK54wHKPpKnVCCP-u9X3Jr8AdpDVAEKgKvaih=s1920-c-rp-mo-br100",
  },
  {
    n: "איציק זקן",
    t: "מכשיר מושלם, שירות אישי ויחס מדהים אחלה מוצר,מומלץ",
    d: "אפריל 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocLK8KNUklKdsI350MyrxrLXNUS4txwAKCkSSTlQBiueQ3JFdg=s1920-c-rp-mo-br100",
  },
  {
    n: "uriel cohen",
    t: "תודה על השרות, אחלה ריחות .",
    d: "אפריל 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocJcLM5x3b-WE-ey5hVU3ONv--HwKk1C9433NO2PvUfZNfbAYQ=s1920-c-rp-mo-br100",
  },
  {
    n: "Liel dabush",
    t: "ריחות מדהימים מכשיר שמעוצב בשיא הסטייל ומעל לכל שירות ויחס מעולים!! אותי קניתם👌👌 יותר נכון מהיום אני קונה רק אצל אודי!",
    d: "אפריל 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocK4ClZ7gQSORnIkhiPiJMHOYR18EWfDok5LXgIWMAwsNwtv3A=s1920-c-rp-mo-br100",
  },
  {
    n: "אורטל ישייב",
    t: "רכשתי את המכשיר שירות מעולה הגיע בזמן קצר והריח מדהיםםםם הבית מריח נפלאאאא",
    d: "אפריל 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocJZO01SZ7IK4Oh-cRsViVW6E0oq96AogLDc4JnDERFGF2d6fw=s1920-c-rp-mo-br100",
  },
  {
    n: "Simon Gawi",
    t: "הזמנתי מכשיר עם שמנים. הגיע מהר , שירות מעולה וגם אחרי הרכישה השירות נשאר טופ. מומלץ מאוד.",
    d: "אפריל 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocLp8SFO_AKbBCoeMQdIMEfkIaWmb0URv50b0PUz-9SxOjS3Gw=s1920-c-rp-mo-br100",
  },
  {
    n: "שרון שכטר",
    t: "ריחות מעולים, שירות מהיר ומצוין. ממליץ בחום",
    d: "אפריל 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocJRmjeSqxxN8KMvtfuac0CBZwy5LOINjF5RUAJw9YkcG4mm2w=s1920-c-rp-mo-br100",
  },
  {
    n: "לירן בר טוב",
    t: "שירות מעל ומעבר למצופה רכשתי מכשיר הגיע ארוז, מהר על כול שאלה ששאלתי קיבלתי יחס ושירות מצוין לגמרי ממליצה",
    d: "אפריל 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocIRM04hK4apTB5tSKrOqh0GjDyphwUwCqM12K18AEHnjluHvw=s1920-c-rp-mo-br100",
  },
  {
    n: "אביה גולן",
    t: "מפיץ מטורף. איכותי וקומפקטי מאוד. אהבתי ממש ! הריחות חלומיים ממליצה",
    d: "אפריל 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocKgAC4OA6x230tqe8-BZH03pWHtAnbCnOnkayfOA3OhUpOz_Q=s1920-c-rp-mo-br100",
  },
  {
    n: "עדן בובליל",
    t: "מפיצים מעולים, מקבלת מחמאות תמיד כשמישהו נכנס הביתה! שירות מעולה ומחיר הגון אין עליהם",
    d: "מרץ 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocIhaBUrqXU1JoC9EAFfwAg45FCUnOq1yA-h9w5UUvpx26HznA=s1920-c-rp-mo-br100",
  },
  {
    n: "Ortal Loutaty",
    t: "שירות נהדר, ריח מעולה בהחלט אזמין שוב ואמליץ לכל מכריי! ממילמה בחום במיוחד טרם החג",
    d: "מרץ 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocL6GngZZJaWxiMK0BOW56z-J_QI0XpNGLPnA-Ihogfi4qMj9w=s1920-c-rp-mo-br100",
  },
  {
    n: "Ramez Knany",
    t: "היום קיבלתי את מפיץ הריח של חברת גראז, ואני פשוט מרוצה! המכשיר נראה נהדר, והוא יצר שינוי משמעותי באווירה עם ריח ייחודי ומרענן לחדר. בנוסף, השירות היה מהיר ואדיב, וקיבלתי יחס נהדר לאורך כל הדרך. ממליץ בחום לכל מי שמחפש פתרון איכותי לריח נעים בבית – שווה כל רגע!",
    d: "מרץ 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocJtTZM9mFVXxaRdjW6PzxZ3BrtF8eezinJwZc2CVZnPw4tf9w=s1920-c-rp-mo-br100",
  },
  {
    n: "איתי אבודרהם",
    t: "שירות אמין ומוצר טוב מאוד",
    d: "מרץ 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocJi48eVMP1qspHSCRBz3lAGaoyGNou_dKw_EXmRZJFsHOdvAQ=s1920-c-rp-mo-br100",
  },
  {
    n: "Kobi Abudram",
    t: "מגוון רחב ואיכותי של ריחות",
    d: "מרץ 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocLaX7z-Z1LVevitL8RAIXOTdUcaCL0O5SX86w_QZ-NArqCbSw=s1920-c-rp-mo-br100",
  },
  {
    n: "רועי אמון",
    t: "ריחות מדהימים ושירות נפלא.",
    d: "מרץ 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocIge60B3GAlJ7Rm1w9pt4ixXWIGF-oeDnkTO3n09rqEXcG6Mg=s1920-c-rp-mo-br100",
  },
  {
    n: "אילנית אמון",
    t: "אחלה שירות שבעולם! אין על אודי הריחות מטריפים!",
    d: "מרץ 2025",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjWxRoSoAoko3326BMhMyBf_0eez4L8mQBul4shwR0OMmY1DtA=s1920-c-rp-mo-br100",
  },
  {
    n: "Tali Maman",
    t: "מכשיר מעולה, שירות פצצה! וריחות אמאלהההה מומלץ ביותר!",
    d: "מרץ 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocLd1IeAomYqA7I4RpUWna1a9PvDedjqghfUMXCI9jbzBQ4ASQ=s1920-c-rp-mo-br100",
  },
  {
    n: "מירב איטח",
    t: "וואו פשוט וואו אין הרבה מה להגיד השרות האדיבות ומפיץ ריח פשוט מדהים עושה את העבודה תודה רבה לכם אני כמובן ממליצה בחום",
    d: "מרץ 2025",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjU6erBY5q2cMLMKJCXg8O9DFMysUVfHiy38R-AXBVkzG30J2kmVjw=s1920-c-rp-mo-br100",
  },
  {
    n: "ירדן אליהו",
    t: "איזה ריחות יש לי בבית בזכותך!!!!!!",
    d: "מרץ 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocKgFEfTs3uyLCOzq0Fhhn6dN0mmhEHdLM33XNqxcI1CoO_c5g=s1920-c-rp-mo-br100",
  },
  {
    n: "מאור דדון",
    t: "איזה ריח מדהים הבית כמו בית מלון",
    d: "מרץ 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocIz4PYAwVCAVjkvi9rmz08YEajGDya8wKgy5IKgamU6FnVhXA=s1920-c-rp-mo-br100",
  },
  {
    n: "Evyatar Elisha",
    t: "אין על השירות שלכםםםםם!!!!",
    d: "מרץ 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocI49kl8n8ppysNu3Ch-e8DwynRqqm-gCB6AOIuyK4Xsr6qY2w=s1920-c-rp-mo-br100",
  },
  {
    n: "חני סן",
    t: "ממליצה בחום על המפיץ ריח ובכלל על השרות האישי שלהם ❤️",
    d: "מרץ 2025",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjW7vR3X2ZAvRazwvKMgoT5Em38SzFZHO5l8RMWffWskWlBt1yUV_g=s1920-c-rp-mo-br100",
  },
  {
    n: "אוהד חקק",
    t: "מעבר למוצר שהוא הכרחי לכל בית בעיניי. המוצר גם מעולה! והשירות שזה הכי חשוב הוא מעל הכל. גם ב-22:00 בלילה קיבלתי מענה ועזרה מהם. שזה מבחינתי שווה עולם. וכמובן הריחות😍😍😍😍",
    d: "מרץ 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocJcvyrJn0qR5iL9YukVBDs_QfgldDX0824mp2RvuG6b_JhSow=s1920-c-rp-mo-ba12-br100",
    lg: 1,
  },
  {
    n: "אסף אדרי",
    t: "רכישה מהירה, מוצר איכותי ושירות לקוחות הכי טוב שקיים, ממליץ בחום.",
    d: "מרץ 2025",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjW5biumxjsn6TIJuBHTXMiGkcSxFVQBJFW9LuOrDRHbTm_y0t8=s1920-c-rp-mo-br100",
  },
  {
    n: "שלומי וקנין",
    t: "יש לי את המכשיר של הרכב, עף עליו בטירוף! ויש להם אחלה שירות",
    d: "פברואר 2025",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjWXgDPYuZniNFggXy01GqFcAk1GTy7vptBMpQ-sUY3R1PBCUwE6-g=s1920-c-rp-mo-ba12-br100",
    lg: 1,
  },
  {
    n: "זיטה דני",
    t: "מכשיר מצעויין / יש לי 5...גם בבית גם במשרד גם במכונית/ שירות מאולה !!!!!",
    d: "פברואר 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocI-lOwofYCHTZsq-QDTmkqOOhGo9X63X6NdDzdOpZzV5BqMRg=s1920-c-rp-mo-br100",
  },
  {
    n: "דרגסטור הצומת",
    t: "שרות מעולה, מכשיר ברמה גבוהה. מאד מרוצה",
    d: "פברואר 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocImaxO-s_QJvMgbzkkz3mPAiUukaWjFRZCiv1OKYfKmCwku7Q=s1920-c-rp-mo-br100",
  },
  {
    n: "Alon Amir",
    t: "קניתי את המפיץ ריח. ריח מעולה כל מי שנכנס לבית מתלהב מהריח. ממש בית מלון 5 כוכבים⭐️⭐️⭐️⭐️⭐️",
    d: "פברואר 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocJvy5h3uWiIOdyTTB4p5TbVW-pInkiGf3kqtdR351wLRnXFpA=s1920-c-rp-mo-br100",
  },
  {
    n: "אביגיל כהן",
    t: "שירות מעולה כל בעיה שיש לי אני שולחת להם הודעה והם עונים לי בסבלנו רבה אפילו צוחקים איתם 😅😅 גם השאלה הכי טיפשית הם עונים בצורה ממש נחמדה תודה אבה על השירות🙏❤️",
    d: "פברואר 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocIZqgsl3uCAZ4KQMq2n-1O5-YJdusOciwErjzjmuFPoefOhXEM=s1920-c-rp-mo-br100",
  },
  {
    n: "Pol Yankovich",
    t: "שירות מעולה אחלה מוצר כל הכבוד לכם ♥️ עשר כוכבים!",
    d: "פברואר 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocI91fq1dCBgvT-8BAutymx6W721NseAqOko7jK8xxS48Qvl7g=s1920-c-rp-mo-br100",
  },
  {
    n: "Roi Arbel",
    t: "אחלה שרות מהיר מדויק ומוצר מושלם",
    d: "פברואר 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocJA7q1Pie5I3uspYThqQ9HEo0jkU-H48HwQt82tSlAEpOAqqA=s1920-c-rp-mo-br100",
  },
  {
    n: "vered hillel",
    t: "שירות מהיר וטוב כן ירבו בארץ מקומות כאלה. רוצה להודות לאודי שנותן הרגשה ממש טובה ואכפתיות❤️ והמוצר מעולה ריח טוב תפעול קל ופשוט 🔥🔥",
    d: "פברואר 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocKl0EK2VB4MygcD3AO3qagMPeOkhNO0xRnBIG3VBgNZkJENjQ=s1920-c-rp-mo-ba12-br100",
    lg: 1,
  },
  {
    n: "אורנית ושי בוטרא",
    t: "ממליצים בחום רכשנו 2 מכשירים מוצר מעולה ריחות בבית שלמות והכי חשוב שרות מדהים",
    d: "פברואר 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocK9Y-Eajbs1EVMqYWxExgAzVeIFxfTToUCR3RfchnQG8PH-_g=s1920-c-rp-mo-br100",
  },
  {
    n: "Ronen Benjamin",
    t: "מוצרים איכותיים, שירות נפלא, מומלץ בחום",
    d: "פברואר 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocIPQQB-jMqNE1aAAR_oD6-71YE0SbITvHClCWpt9kLA-bG5dg=s1920-c-rp-mo-br100",
  },
  {
    n: "פלורי פורטל",
    t: "שרות אמין חוזרים אליכם אם כול בעיה אני מאוד מרוצה",
    d: "פברואר 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocKJPRKANT0hZWC-oGven4YEYROOjf-wQJC2S9ZPSovP_VAL1w=s1920-c-rp-mo-br100",
  },
  {
    n: "הודיה כהן",
    t: "קניתי ומאוד מרוצה. שירות מעולה, ריחות שנשארים הרבה זמן!",
    d: "פברואר 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocLXJCCQDyYq2BBoAFupsN9s9ZzKCGDWS6oEVbx7OQrktcGneQ=s1920-c-rp-mo-br100",
  },
  {
    n: "רותם אליהו",
    t: "פשוט אדיר המוצר הזה. איזה ריחות, איזה שירות. מומלץ בחום .",
    d: "פברואר 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocJdJwhbiYm1_HahH_BdCqvr_Iby_l9vgDNzFU8di-cylOdZGQ=s1920-c-rp-mo-br100",
  },
  {
    n: "לינוי גורנו",
    t: "מוצר נדיר ביותר!!!! אין ריחות כאלה פשוט מושלם!!! מחמיאים בלי סוף על הריח בבית ! מומלץ מומלץ מומלץ והשירות בכללללללל נדיר ! אלופים!",
    d: "פברואר 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocIy4rw_SXlBeubN2iy0Ma-hPndO7ZDHu1t_I_7y2ZfKd9X3CQ=s1920-c-rp-mo-br100",
  },
  {
    n: "hatem khateb",
    t: "מאוד ממליצה ,הריח של הבושם מכסה יותר מהשטח הרשום, אפילו לפני הפעלת המכשיר מריחים את זה",
    d: "פברואר 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocJRd18rpSYdj0_O1EPZEQKQdU4kXBB_ofs_Gt1xwDD_8x0koEI=s1920-c-rp-mo-br100",
  },
  {
    n: "תמר אליהו",
    t: "מכירים את הרגע הזה של הכניסה ללובי בית המלון או לחנות בוטיק יוקרתית כשריח ממכר באויר?? כזה בדיוק רציתי אצלי בבית. אחרי שניסיתי אינסוף מבשמים, שטיפה עם מרכך כביסה, הרתחת מים עם נוזל מבשם וריח שנשמר לדקות בלבד.. כמעט והתייאשתי. עד שנכנסתי לבית השכנים ומיד קלטתי שהם משתמשים במוצר איכותי שלא הכרתי. זה לקח פחות משעתיים מהרגע שיצרתי קשר ועד שאודי הגיע עם מבחר ריחות מטורף, לבחור בין הטוב ביותר למושלם. התקנה פשוטה, הסבר מפורט, שירות יעיל, אדיב ומקצועי, וריח.. שנשמר לאורך כל היום. ומאז.. זה סיפור אהבה.. זה רק האורחים שלא רוצים ללכת.",
    d: "פברואר 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocKziGG5xWXXAxg8fYSgYCRVaVQxH2C2zQDAGugXTm8ebcr7ng=s1920-c-rp-mo-br100",
  },
  {
    n: "maxi aravsky",
    t: "מוד מרוצה מי הקנייה! תודה על השרות",
    d: "פברואר 2025",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjVMmGdFs3AbryEJKkUvhZx2qjMjd5uyj6m67QcAX5cDALSsk_nT=s1920-c-rp-mo-br100",
  },
  {
    n: "Hanan Ohana",
    t: "נתחיל בזה שאודי בעל סבלנות אינסופית וליווי משלב בחירת המפיץ שיתאים בדיוק לצרכים, לחלל ולאופי של הבית שלנו דרך בחירה ממבחר באמת מרשים של ריחות מאוד מוצלחים ועד אחרי שהמפיץ מותקן ועובד. הגדרה והפעלה קלים ופשוטים, חשוב לנו מאוד. המפיץ אסטטי ומשתלב בבית וממלא את הבית בריח משגע. השאלה הראשונה של אנשים שמגיעים אלינו זה ׳מאיפה הריח מגיע?׳ והשאלה השניה היא ׳מה הטלפון של המשווק?׳. זו אחת הרכישות המוצלחות יותר שלנו השנה.",
    d: "פברואר 2025",
    p: "https://lh3.googleusercontent.com/a-/ALV-UjVuXm2m6oz9eToCFwbpBL7oKtNhYgDQ1V6-uvUFSHX8W5PrjJAL=s1920-c-rp-mo-ba12-br100",
    lg: 1,
  },
  {
    n: "Meital Rashti",
    t: "רכשתי את המפיץ ריח והוא פשוט מושלם,לא חזק מדי ומורגש בדיוק במידה הנכונה. בנוסף העיצוב שלו מושלם אם אתם מחפשים פתרון איכותי זאת הבחירה המושלמת",
    d: "פברואר 2025",
    p: "https://lh3.googleusercontent.com/a/ACg8ocKRzS179KhR5vNQ2-vqZ0Er7qhdM8spu18jPuk27nWm2oqWsW3u=s1920-c-rp-mo-br100",
  },
];
